### ISSUE TITLE
Tidy up youtube-dl progress

### ISSUE THREAD

**Issue by snobu** [snobu/destreamer#39]
The current state of our youtube-dl progress output can be described as _apocalyptic_ at best. For example -

![image](https://user-images.githubusercontent.com/6472374/78548335-512a8000-7809-11ea-999f-ba2968d325dd.png)

I propose we either build our own logic to deal with the mess or we use something that already exists out there, like [`ytdl-core`][1]. Example -

```javascript
const readline = require('readline');
const fs = require('fs');
const ytdl = require('ytdl-core');
// TypeScript: import ytdl from 'ytdl-core'; with --esModuleInterop
// TypeScript: import * as ytdl from 'ytdl-core'; with --allowSyntheticDefaultImports
// TypeScript: import ytdl = require('ytdl-core'); with neither of the above

let video = ytdl('https://www.youtube.com/watch?v=UnSILVWDKL8');

let starttime;
video.pipe(fs.createWriteStream('video.mp4'));

video.once('response', () => {
  starttime = Date.now();
});

video.on('progress', (chunkLength, downloaded, total) => {
  const percent = downloaded / total;
  const downloadedMinutes = (Date.now() - starttime) / 1000 / 60;
  readline.cursorTo(process.stdout, 0);
  process.stdout.write(`${(percent * 100).toFixed(2)}% downloaded `);
  process.stdout.write(`(${(downloaded / 1024 / 1024).toFixed(2)}MB of ${(total / 1024 / 1024).toFixed(2)}MB)\n`);
  process.stdout.write(`running for: ${downloadedMinutes.toFixed(2)}minutes`);
  process.stdout.write(`, estimated time left: ${(downloadedMinutes / percent - downloadedMinutes).toFixed(2)}minutes `);
  readline.moveCursor(process.stdout, 0, -1);
});
```

Result -

![progress](https://user-images.githubusercontent.com/6472374/78548483-8afb8680-7809-11ea-813c-71c57ed220de.gif)

Moreover, `terminal-kit` (which we already depend on) has a progress bar, would make for a really neat UI -
![](https://raw.githubusercontent.com/cronvel/terminal-kit/master/sample/progress-bar-doc1.gif)

[1]: https://github.com/fent/node-ytdl-core

Passing `--verbose` would change this neat output to raw youtube-dl output when debugging is necessary.

**Comment by snobu** [comment]
ytdl-core is a dead end since it's not a youtube-dl wrapper, it's a new implementation that does DOM parsing and is youtube specific. What we need is a youtube-dl output parser.

**Comment by kylon** [comment]
i tried to make a progress bar a few days ago but i gave up for 2 reasons:

1
are we switching to aria? if yes, i think there s no need to waste time on this

2
youtube-dl has no output, let me explain

my idea was to grab youtube-dl stdout and make a custom progress bar by parsing every stdout line in real time.
the problem here is that i found that youtube-dl does nothing, all the mess you see is ffmpeg.

so you spawn youtube-dl -> youtube-dl prepares ffmpeg -> youtube-dl launches ffmpeg.

afaik, when you spawn a child in node you can get its stdout, but if your child spawns a new child, you will have no control over it.
what we need here is ffmpeg output.

i tried many node libraries but none of them was able to show the ffmpeg output, i don't know if there is an hack or a hidden lib that can do this.

the only solution i see now is that youtube-dl should implement a progress bar. (unless there is an arg that i m not aware of to get some useful output)

**Comment by snobu** [comment]
I'm trying out a few things of my own, will report back progress. I'll have a closer look ar aria2c as well.

**Comment by snobu** [comment]
There's a - - show-json in youtube-dl or something like that which i believe generates something sanely parsable. Didn't look too much into it yet.

**Comment by lukaarma** [comment]
If you really want to implement aria2c I have *some* experience working with it, so if you need help I can provide some

**Comment by snobu** [comment]
@kylon raised a valid point. Why even take a dependency on youtube-dl to begin with.

This seems to work just as fine -

```
`ffmpeg -headers "Authorization: Bearer ${session.AccessToken}" -i "${video.playbackUrl}" video.mp4`;
```

..which now opens up a new can of worms:
https://www.npmjs.com/search?q=ffmpeg%20progress

**Comment by lukaarma** [comment]
There are only 3 packages in the page that you linked that were updated in the last year, only 2 in the last 6 months

We should pick one and focus all our collective efforta towards that one

**Comment by snobu** [comment]
So i replaced our youtube-dl command logic with `fluent-ffmpeg`.

**Comment by kylon** [comment]
the error says unknown option

this is the syntax in that issue
command.inputOption('-headers', 'Header1: value\r\nHeader2: value...')

have you tried to split -headers and its value.

i had the same problem with node spawn syntax

**Comment by snobu** [comment]
Yes, thank you! That was it. It was driving me insane.

**Comment by snobu** [comment]
Ok, i have some progress -

```
console.info('Spawning ffmpeg with access token and HLS URL...');
        ffmpeg()
          .input(`"${video.playbackUrl}"`)
          .inputOption([
            '-headers', `"Authorization:Bearer ${session.AccessToken}"`,
          ])
          .format('mp4')
          .saveToFile(`"${outputDirectory}/${video.title}.mp4"`)
          .on('start', cmd => {
            console.log(`Spawned Ffmpeg with command: ${cmd}`);
          })
          .on('codecData', data => {
            console.log(`Input is ${data.video} with ${data.audio} audio.`);
          })
          .on('progress', progress => {
            console.log(`Processing: ${progress.percent} % done`);
          })
          .on('stderr', stderr => {
            console.log(`Stderr output: ${stderr}`);
          })
          .on('error', err => {
            console.log(`An error occurred: ${err.message}`);
          })
          .on('end', info => {
            console.log(`Processing finished: ${info}`);
          });
```

Now i'm errorring out on
```
Stderr output: "https://use2-2.api.microsoftstream.com/api/videos/manifest?api-version=1.0\&playbackurl=https://e22-blah-blah-tbna.ism/manifest(format=m3u8-aapl)": No such file or directory
```

most likely due to this https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/843

**Comment by snobu** [comment]
I've pushed this to `tokencache` to ease debugging.

**Comment by lukaarma** [comment]
I have a different error from you I think, take a look:

<details>
<summary>Error</summary>

Spawned Ffmpeg with command: ffmpeg -headers "Authorization:Bearer BIG_OLE:AUTHKEY" -i https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://BLABLA-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/manifest(format=m3u8-aapl) -y -f mp4 "videos/TITLE"

Stderr output: ffmpeg version git-2020-03-30-8d019db Copyright (c) 2000-2020 the FFmpeg developers
Stderr output:   built with gcc 9.3.1 (GCC) 20200328
Stderr output:   configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf

Stderr output:   libavutil      56. 42.102 / 56. 42.102
Stderr output:   libavcodec     58. 77.101 / 58. 77.101
Stderr output:   libavformat    58. 42.100 / 58. 42.100
Stderr output:   libavdevice    58.  9.103 / 58.  9.103
Stderr output:   libavfilter     7. 77.101 /  7. 77.101
Stderr output:   libswscale      5.  6.101 /  5.  6.101
Stderr output:   libswresample   3.  6.100 /  3.  6.100
Stderr output:   libpostproc    55.  6.100 / 55.  6.100

Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-VERSION:4')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=165532,RESOLUTION=320x180,CODECS="avc1.64000c",URI="https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(19000)/Manifest(video,format=m3u8-aapl,type=keyframes)"')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=195170,RESOLUTION=640x360,CODECS="avc1.640016",URI="https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(48000)/Manifest(video,format=m3u8-aapl,type=keyframes)"')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=225830,RESOLUTION=960x540,CODECS="avc1.64001f",URI="https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(78000)/Manifest(video,format=m3u8-aapl,type=keyframes)"')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=258534,RESOLUTION=1280x720,CODECS="avc1.64001f",URI="https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(110000)/Manifest(video,format=m3u8-aapl,type=keyframes)"')
Stderr output: [hls @ 000001c50b57d1c0] Opening 'https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(127000)/Manifest(aac_eng_2_127_1_1,format=m3u8-aapl)' for reading
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-VERSION:4')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-ALLOW-CACHE:NO')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
Stderr output: [https @ 000001c50b916040] Opening 'https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(19000)/Manifest(video,format=m3u8-aapl)' for reading
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-VERSION:4')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-ALLOW-CACHE:NO')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
Stderr output: [https @ 000001c50b916040] Opening 'https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(48000)/Manifest(video,format=m3u8-aapl)' for reading
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-VERSION:4')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-ALLOW-CACHE:NO')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
Stderr output: [https @ 000001c50b916040] Opening 'https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(78000)/Manifest(video,format=m3u8-aapl)' for reading
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-VERSION:4')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-ALLOW-CACHE:NO')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
Stderr output: [https @ 000001c50b916040] Opening 'https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(110000)/Manifest(video,format=m3u8-aapl)' for reading
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-VERSION:4')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-ALLOW-CACHE:NO')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
Stderr output: [https @ 000001c50b916040] Opening 'https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackUrl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(127000)/Manifest(aac_eng_2_127_1_1,format=m3u8-aapl)' for reading
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-VERSION:4')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-ALLOW-CACHE:NO')
Stderr output: [hls @ 000001c50b57d1c0] Skip ('#EXT-X-PROGRAM-DATE-TIME:1970-01-01T00:00:00Z')
Stderr output: [hls @ 000001c50b57d1c0] Opening 'https://euwe-1.api.microsoftstream.com/api/videos/VIDEO_ID_HERE/protectionKey?api-version=1.0' for reading
Stderr output: [hls @ 000001c50b57d1c0] Unable to open key file https://euwe-1.api.microsoftstream.com/api/videos/VIDEO_ID_HERE/protectionKey?api-version=1.0
Stderr output: [hls @ 000001c50b57d1c0] Opening 'crypto+https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(127000)/Fragments(aac_eng_2_127_1_1=0,format=m3u8-aapl)' for reading
Stderr output: [hls @ 000001c50b57d1c0] Opening 'crypto+https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(127000)/Fragments(aac_eng_2_127_1_1=60160000,format=m3u8-aapl)' for reading
Stderr output: [hls @ 000001c50b57d1c0] Error when loading first segment 'https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/QualityLevels(127000)/Fragments(aac_eng_2_127_1_1=0,format=m3u8-aapl)'
Stderr output: https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/manifest(format=m3u8-aapl): Invalid data found when processing input
Stderr output: 
An error occurred: ffmpeg exited with code 1: https://euwe-1.api.microsoftstream.com/api/videos/manifest?api-version=1.0&playbackurl=https://SAME_CODE_HERE-euwe.streaming.media.azure.net/SOMEID/SOME_OTHER_CODE.ism/manifest(format=m3u8-aapl): Invalid data found when processing input
</details>

**Comment by snobu** [comment]
Got it working. It's a fine and silly art passing arguments to ffmpeg. I miss youtube-dl :)

```
        ffmpeg()
          .input(video.playbackUrl)
          .inputOption([
            '-headers', `Authorization:\ Bearer\ ${session.AccessToken}`
          ])
          .format('mp4')
          .saveToFile(`${outputDirectory}${path.sep}${video.title}.mp4`)
...
```
Lessons learned: Don't try to pass in double quotes, whitespace in headers MUST be escaped, ALWAYS. I figured this out via `ffmpeg -loglevel debug`.t

Pushed to `tokencache`.

**Comment by lukaarma** [comment]
nice work @snobu, it's working flawlessly 🔝

**Comment by snobu** [comment]
So, we have 

```
.on('progress', progress
```

and `progress.timemark` has the current HLS segment as absolute video timestamp.

In theory we need to find out how to query for video length (in minutes/seconds/whatever) either from API or ffmpeg, then draw our own progress bar from total_video_time minus current timemark.

We can do all that via frame numbers as well if it's easier. `progress.frames` has total video frames and `progress.currentFps` has fps. We can apply simple math times hope and dreams (since fps may drop) and estimate a progress bar position.

What can i say more...
![seal](https://user-images.githubusercontent.com/6472374/78924233-18f19e80-7aa2-11ea-9bc3-3ef692c1f7f5.gif)

**Comment by snobu** [comment]
This lib looks really nice, a little fat at 50KB unpacked, maybe we can find a simpler implementation since we don't need much.
https://www.npmjs.com/package/cli-progress

**Comment by lukaarma** [comment]
@snobu there's a way to implement simulate in ffmpeg (as I'm not finding any in the docs)?

**Comment by snobu** [comment]
I don't think so. I think we need to rewrite that feature to simply get the access token and return a few stats at the end like video title, output file and so on, without calling ffmpeg at all... or maybe we could call ffmpeg just to get AV codec info.

**Comment by lukaarma** [comment]
I'm going to look into implementing the simulation flag as best as I can tomorrow

**Comment by snobu** [comment]
I may have just found our solution that requires zero effort on our side -

![wat](https://user-images.githubusercontent.com/6472374/78983521-0a9c9480-7b2d-11ea-9005-9db7ea2e650a.gif)

via https://github.com/sidneys/ffmpeg-progressbar-cli.

**Comment by snobu** [comment]
Just pushed to `tokencache`, need to test this on Windows as well, looks fantastic on the Mac.

**Comment by lukaarma** [comment]
ok when we call the script we have to check what platform we are on because now it doesn't work on windows (there's a PS and a CMD one too)

**Comment by kylon** [comment]
this thing is not working well on my term, i think a cross platform module is better

**Comment by kylon** [comment]
i think we can nuke this package and use something simpler

we have the duration and ffmpeg has the current timemark

trying something like this
https://www.npmjs.com/package/progress

**Comment by snobu** [comment]
Ah i see, yeah ffmpeg-bar looked so promising. Got excited too soon.

**Comment by kylon** [comment]
working cross-platform? progressbar
tested on linux and win 10 powershell
messy code, but it is not important right now

can you try this on both win and mac? thanks
@snobu @lukaarma 

tokencache branch has a broken downloadVideo function, the promise is not working so do not input more than one url

[destreamer.ts.zip](https://github.com/snobu/destreamer/files/4463758/destreamer.ts.zip)

**Comment by snobu** [comment]
Can you please push to a new branch here? Not sure what to pick as base for your .zip since we've merged a few things in since.

**Comment by snobu** [comment]
Also, you know we just need to make this usable for now it doesn't have to be perfect, 

![IMG_20200411_143828](https://user-images.githubusercontent.com/6472374/79042754-f0cd8100-7c02-11ea-9f1b-2bc318d26151.jpg)

**Comment by kylon** [comment]
#57 

yeah, i don't relly like refactoring, i prefer to write good code :P 

anyway, this branch is not ready, it is still not fully working

**Comment by snobu** [comment]
Well, in our join defense, we changed like 60% of the code from dev so it's expected. Nobody is in a hurry, i agree let's write good code, no pressure.

**Comment by snobu** [comment]
Closing since our progress bar is now clean and stable. Thanks @kylon!
