### ISSUE TITLE
v2.0 RELEASE

### ISSUE THREAD

**Issue by snobu** [snobu/destreamer#70]
I've pushed the `master` branch as our 2.0 Release. Let's await some issues, if none show up let's make a fresh roadmap, that may include -

- [ ] Binary release (via pkg?, @kylon already has a working version of this). We should use a GitHub Action to package for all major OSes and publish under the Releases tab.
- [ ] aria2c? Is it really that much faster than ffmpeg? Do we have a benchmark against Azure Media Services endpoints?

All other branches are now deprecated.
I'd rather delete them all (except for `dev` since people are still pulling that to update their current destreamer). **@kylon @lukaarma do you still need the other branches lingering around or can i obliterate them?**

I've added a deprecation warning (both README and console.log in code) to the dev branch.

**Comment by kylon** [comment]
#64 this is also ready
if it is ok, i'll update the readme

i don't need the other branches

i'm not sure about aria2c, i know that someone is already using it with destreamer but they got mixed results when downloading more than 1 video, i don't want destreamer to fail randomly because then you can't throw a list at it and leave your pc, i would rather wait more but with 100% success rate

**Comment by snobu** [comment]
I fixed #62 before pushing out master, or at least i hope i did. Let me try that again.

**Comment by kylon** [comment]
missed the new commits

**Comment by kylon** [comment]
i think you missed the case where the token expires while a video is being downloaded, you have no way to generate a new token and refresh token should receive 401
the next download will fail

you should create a new thread to refresh the token, set a timeout on destreamer start equal to token minutes, or "token expire - 10" if you are creating a new token
this way the token will never expire mid download

**Comment by snobu** [comment]
Yes, that's still an outstanding bug, i'll just put a note right now in the README describing the problem.
Unrelated,  looks like aria2c does not have HLS support -- https://github.com/aria2/aria2/issues/1271

@lukaarma is there maybe a fork that has this support baked in?

**Comment by lukaarma** [comment]
> @kylon @lukaarma do you still need the other branches lingering around or can i obliterate them?
Nuke em

> @lukaarma is there maybe an aria fork that has this support baked in?

Not that I know about, what I was experimenting with was to download the encrypted chunks with aria2c and then run them through ffmpeg

**Comment by snobu** [comment]
Oh i see, that's a good idea. Feel free to create a new branch and give it a go. I'm open to it if we have a good way of limiting the number of threads (not really threads is my worry here but total download speed). We should strive to keep our end goal of not abusing the endpoints beyond what a browser would do, otherwise
![image](https://user-images.githubusercontent.com/6472374/79640531-ba5fab00-819a-11ea-83d4-90affcbd9040.png)

**Comment by lukaarma** [comment]
Already took a look and from what I gathered it does pretty much the same thing except it uses all the parallel connection possible, abusing the endpoints

I don't really have too much time now, exams to do, but I'll see if and what I can come up with

**Comment by snobu** [comment]
Also this -
https://github.com/sup3rgiu/PoliDown/blob/master/polidown.js#L75-L79

This is a bad idea for default behaviour, however would be a very interesting option.. as an option. Won't work for all tenants but would be fine for most (and 2FA would be fine as well since we still spin up a browser). Not sure if that thing works on Windows as well, the keytar readme briefly mentions it without being assertive.

**Comment by snobu** [comment]
@lukaarma as always, this is a best effort project, no strong commitments are allowed or encouraged :) Good luck with exams!

**Comment by snobu** [comment]
v2.0 released as the master branch. Let's take the ideas floated in this thread and open individual issues.
